version: '2.1'

services:
  proxy:
    image: nginx
    environment:
      DNSDOCK_ALIAS: 'redmine.docker'
    ports:
      - 80
    links:
      - redmine
    network_mode: bridge
    volumes:
      - ./config/docker/nginx/redmine.docker:/etc/nginx/conf.d/default.conf

  redmine:
    image: redmine:3.2
    restart: always
    ports:
      - 3000
    network_mode: bridge
    links:
      - db
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    volumes:
      - ./images:/usr/src/redmine/public/themes/synbioz/images
      - ./javascripts:/usr/src/redmine/public/themes/synbioz/javascripts
      - ./stylesheets:/usr/src/redmine/public/themes/synbioz/stylesheets
      - ./plugins:/usr/src/redmine/plugins
      - ./plugins/redspot/assets:/usr/src/redmine/public/plugin_assets/redspot

  db:
    image: mysql:5.7
    restart: always
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - /var/lib/docker/data/mysql/redmine:/var/lib/mysql
